apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 2000
      derivedFields:
        # Menghubungkan log berdasarkan request_id yang sama (tracing correlation)
        - datasourceUid: Loki
          matcherRegex: '"request_id":\s*"([^"]+)"'
          name: RequestID
          url: '$${__value.raw}'
